### PR TITLE
Refactor all thrown errors to `IgnitionError`s

### LINKED ISSUE #100: Improve cli errors
We are showing a stack trace for some cli level errors:

image

We should figure out if we are throwing the wrong error type for these cli errors i.e. no module with that name.

Whatever the reason the outcome should be error messages that look more like HH.

### LINKED ISSUE #117: Switch default on confirm against network
Our non-hardhat confirmation defaults to yes, we should default to no:

image

### PR DESCRIPTION
**Pull request by zoeyTM**
Screen Shot 2023-01-24 at 8 18 43 AM

closes #100 
closes #117

### CODE REVIEW

**Comment by morgansliman** [comment]
Oh, closes #117 too. Threw that in here since it's just a one-liner

**Review by kanej — APPROVED** [review]
LGTM!

**Comment by kanej** [comment]
I took a quick look for an eslint rule that would enforce not using `Error` but no luck. Seems I will just have to remember.

**Comment by zoeyTM** [comment]
Going to wait until [this](https://github.com/NomicFoundation/hardhat/pull/3658) is merged and released, then I'll add it to this PR

**Pull request merged**
